--
-- File generated with SQLiteStudio v3.2.1 on Tue Jun 9 20:53:46 2020
--
-- Text encoding used: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: child_guardian
DROP TABLE IF EXISTS child_guardian;
CREATE TABLE child_guardian (id INTEGER PRIMARY KEY AUTOINCREMENT, child INTEGER REFERENCES person (id) ON DELETE CASCADE ON UPDATE CASCADE, guardian INTEGER REFERENCES person (id) ON DELETE CASCADE ON UPDATE CASCADE, note STRING);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (1, 1, 7, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (2, 1, 8, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (3, 2, 7, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (4, 2, 8, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (5, 3, 7, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (6, 3, 8, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (7, 13, 11, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (8, 14, 11, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (9, 15, 11, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (10, 13, 12, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (11, 14, 12, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (12, 15, 12, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (13, 18, 16, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (14, 19, 16, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (15, 18, 17, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (16, 19, 17, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (17, 22, 20, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (18, 23, 20, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (19, 22, 21, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (20, 23, 21, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (21, 26, 24, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (22, 26, 25, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (23, 27, 24, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (24, 27, 25, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (25, 30, 28, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (26, 30, 29, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (27, 31, 28, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (28, 31, 29, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (29, 32, 28, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (30, 32, 29, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (31, 33, 28, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (32, 33, 29, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (33, 36, 34, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (34, 36, 35, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (35, 37, 34, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (36, 37, 35, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (37, 38, 34, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (38, 38, 35, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (39, 41, 39, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (40, 41, 40, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (41, 42, 39, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (42, 42, 40, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (43, 43, 39, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (44, 43, 40, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (45, 44, 39, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (46, 44, 40, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (47, 47, 45, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (48, 47, 46, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (49, 48, 45, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (50, 48, 46, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (51, 49, 45, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (52, 49, 46, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (53, 52, 50, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (54, 52, 51, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (55, 53, 50, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (56, 53, 51, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (57, 60, 54, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (58, 60, 55, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (59, 61, 54, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (60, 61, 55, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (61, 62, 54, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (62, 62, 55, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (63, 63, 54, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (64, 63, 55, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (65, 64, 54, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (66, 64, 55, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (67, 4, 9, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (68, 4, 10, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (69, 5, 9, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (70, 5, 10, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (71, 6, 9, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (72, 6, 10, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (73, 65, 58, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (74, 65, 59, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (75, 66, 58, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (76, 66, 59, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (77, 67, 58, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (78, 67, 59, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (79, 68, 56, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (80, 68, 57, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (81, 69, 56, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (82, 69, 57, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (83, 70, 56, NULL);
INSERT INTO child_guardian (id, child, guardian, note) VALUES (84, 70, 57, NULL);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
